# Generated by Django 6.1 on 2026-08-23 16:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auditoria', '0002_initial'),
        ('donacion', '0001_initial'),
        ('nutricion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fractionation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fractionation_number', models.CharField(max_length=20, unique=True)),
                ('fractionation_date', models.DateTimeField()),
                ('total_volume_ml', models.DecimalField(decimal_places=2, max_digits=8)),
                ('responsible', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DonorDismissal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dismissal_date', models.DateTimeField()),
                ('reason', models.TextField()),
                ('dismissed_by', models.CharField(max_length=100)),
                ('can_reenter', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donor_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='donacion.donacion')),
            ],
        ),
        migrations.CreateModel(
            name='FractionatedBottle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qr_code', models.CharField(max_length=30, unique=True)),
                ('volume_ml', models.DecimalField(decimal_places=2, max_digits=8)),
                ('milk_stage', models.CharField(choices=[('colostrum', 'Calostro'), ('transition', 'Transición'), ('mature_low', 'Madura baja'), ('mature_high', 'Madura alta')], max_length=20)),
                ('target', models.CharField(choices=[('preterm', 'Prematuro'), ('term', 'Término')], max_length=20)),
                ('calories_kcal', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('expiration_date', models.DateField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('used', 'Used'), ('discarded', 'Discarded')], default='available', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fractionation_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bottles', to='procesamiento.fractionation')),
            ],
            options={
                'verbose_name_plural': 'Fractionated Bottles',
            },
        ),
        migrations.CreateModel(
            name='MilkBatches',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('barcode', models.CharField(max_length=30, unique=True)),
                ('batch_number', models.IntegerField()),
                ('collection_date', models.DateTimeField()),
                ('volume_ml', models.DecimalField(decimal_places=2, max_digits=8)),
                ('milk_stage', models.CharField(choices=[('colostrum', 'Calostro'), ('transition', 'Transición'), ('mature_low', 'Madura baja'), ('mature_high', 'Madura alta')], max_length=20)),
                ('target', models.CharField(choices=[('preterm', 'Prematuro'), ('term', 'Término')], max_length=20)),
                ('calories_kcal', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('status', models.CharField(default='raw', max_length=20)),
                ('storage_temp', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('expiration_date', models.DateField()),
                ('responsible', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('center_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='donacion.collectioncenter')),
                ('donor_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='donacion.donacion')),
                ('visit_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='donacion.visit')),
            ],
            options={
                'verbose_name_plural': 'Milk Batches',
            },
        ),
        migrations.CreateModel(
            name='InternalExtraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('extraction_date', models.DateTimeField()),
                ('scheduled_time', models.TimeField(blank=True, null=True)),
                ('volume_ml', models.DecimalField(decimal_places=2, max_digits=8)),
                ('used_immediately', models.BooleanField(default=False)),
                ('frozen', models.BooleanField(blank=True, default=False, null=True)),
                ('responsible', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donor_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='donacion.donacion')),
                ('extraction_staff_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auditoria.staff')),
                ('patient_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='nutricion.patient')),
                ('batch_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='procesamiento.milkbatches')),
            ],
        ),
        migrations.CreateModel(
            name='PasteurizationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('new_barcode', models.CharField(max_length=30, unique=True)),
                ('pasteurization_date', models.DateTimeField()),
                ('method', models.CharField(max_length=20)),
                ('temp_celsius', models.DecimalField(decimal_places=2, max_digits=5)),
                ('duration_min', models.IntegerField()),
                ('volume_ml', models.DecimalField(decimal_places=2, max_digits=8)),
                ('milk_stage', models.CharField(choices=[('colostrum', 'Calostro'), ('transition', 'Transición'), ('mature_low', 'Madura baja'), ('mature_high', 'Madura alta')], max_length=20)),
                ('target', models.CharField(choices=[('preterm', 'Prematuro'), ('term', 'Término')], max_length=20)),
                ('calories_kcal', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('acidity_dornic', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('cream_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fat_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('kcal_per_liter', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('culture_24h_result', models.CharField(choices=[('pending', 'Pending'), ('negative', 'Negative'), ('positive', 'Positive')], default='pending', max_length=20)),
                ('culture_24h_date', models.DateField(blank=True, null=True)),
                ('culture_48h_result', models.CharField(choices=[('pending', 'Pending'), ('negative', 'Negative'), ('positive', 'Positive')], default='pending', max_length=20)),
                ('culture_48h_date', models.DateField(blank=True, null=True)),
                ('quality_result', models.CharField(default='pending', max_length=20)),
                ('bacterial_count', models.IntegerField(blank=True, null=True)),
                ('responsible', models.CharField(max_length=100)),
                ('discarded', models.BooleanField(default=False)),
                ('discard_reason', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='procesamiento.milkbatches')),
            ],
        ),
        migrations.AddField(
            model_name='fractionation',
            name='pasteurization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fractionations', to='procesamiento.pasteurizationrecord'),
        ),
    ]
