# Generated by Django 6.1 on 2026-08-23 16:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('brand', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=30)),
                ('presentation', models.CharField(blank=True, max_length=50, null=True)),
                ('unit_measure', models.CharField(max_length=20)),
                ('calories_kcal_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('min_stock_alert', models.IntegerField(default=10)),
                ('requires_prescription', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(max_length=30)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.UUIDField()),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], max_length=20)),
                ('message', models.TextField()),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('acknowledged_by', models.CharField(blank=True, max_length=100, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockExit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exit_type', models.CharField(max_length=30)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_measure', models.CharField(max_length=20)),
                ('exit_date', models.DateTimeField()),
                ('reason', models.CharField(max_length=30)),
                ('responsible', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(max_length=30)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_measure', models.CharField(max_length=20)),
                ('lot_number', models.CharField(blank=True, max_length=30, null=True)),
                ('manufacturing_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField()),
                ('supplier', models.CharField(blank=True, max_length=100, null=True)),
                ('purchase_order', models.CharField(blank=True, max_length=50, null=True)),
                ('milk_stage', models.CharField(blank=True, choices=[('colostrum', 'Calostro'), ('transition', 'Transición'), ('mature_low', 'Madura baja'), ('mature_high', 'Madura alta')], max_length=20, null=True)),
                ('target', models.CharField(blank=True, choices=[('preterm', 'Prematuro'), ('term', 'Término')], max_length=20, null=True)),
                ('calories_kcal', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('entry_date', models.DateTimeField()),
                ('responsible', models.CharField(max_length=100)),
                ('pharmacy_request_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('formula_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.formula')),
            ],
        ),
    ]
