# Generated by Django 6.1 on 2026-08-23 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donacion', '0001_initial'),
        ('inventario', '0001_initial'),
        ('nutricion', '0001_initial'),
        ('procesamiento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockentry',
            name='fractionated_bottle_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='procesamiento.fractionatedbottle'),
        ),
        migrations.AddField(
            model_name='stockexit',
            name='center_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='donacion.collectioncenter'),
        ),
        migrations.AddField(
            model_name='stockexit',
            name='patient_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='nutricion.patient'),
        ),
        migrations.AddField(
            model_name='stockexit',
            name='stock_entry_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.stockentry'),
        ),
    ]
