# Generated by Django 6.1 on 2026-08-23 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auditoria', '0001_initial'),
        ('donacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyassignment',
            name='center_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='donacion.collectioncenter'),
        ),
        migrations.AddField(
            model_name='staff',
            name='center_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='donacion.collectioncenter'),
        ),
        migrations.AddField(
            model_name='dailyassignment',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auditoria.staff'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='staff_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='auditoria.staff'),
        ),
    ]
