from . import donante
from . import historia
from . import visita
from . import consentimiento
from . import serologia
from . import frasco
from . import pasteurizacion
from . import fraccionamiento
from . import distribucion
from . import bitacora
from . import stock_leche
from . import rendimiento
from . import paciente
from . import nutricion
from . import alimento
from . import stock_alimento
from . import stock_alimento_resumen
from . import evolucion
from . import dashboard
from . import alerta
from . import res_users
from . import res_partner
from . import asignacion