# Generated by Django 6.1 on 2026-08-22 08:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donacion', '0001_initial'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedingPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('milk_type', models.CharField(blank=True, max_length=20, null=True)),
                ('feeding_type', models.CharField(max_length=30)),
                ('volume_ml_per_feed', models.DecimalField(decimal_places=2, max_digits=6)),
                ('feeds_per_day', models.IntegerField()),
                ('total_daily_ml', models.DecimalField(decimal_places=2, max_digits=8)),
                ('calories_target', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('prescribed_by', models.CharField(max_length=100)),
                ('status', models.CharField(default='active', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('formula_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.formula')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_code', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('birth_weight_g', models.IntegerField(blank=True, null=True)),
                ('gestational_age_weeks', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('sex', models.CharField(max_length=1)),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('admission_date', models.DateField()),
                ('discharge_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mother_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='donacion.donacion')),
            ],
        ),
        migrations.CreateModel(
            name='NutritionTracking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('measurement_date', models.DateField()),
                ('age_days', models.IntegerField()),
                ('weight_g', models.IntegerField(blank=True, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('head_circumference_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bmi', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weight_percentile_oms', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('height_percentile_oms', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('daily_intake_ml', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('daily_kcal', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('recorded_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feeding_plan_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='nutricion.feedingplan')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nutricion.patient')),
            ],
        ),
        migrations.AddField(
            model_name='feedingplan',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nutricion.patient'),
        ),
    ]
