# Generated by Django 6.1 on 2026-08-23 16:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auditoria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionCenter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('responsible', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Donacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('donor_code', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('address', models.TextField()),
                ('blood_type', models.CharField(max_length=5)),
                ('serology_status', models.CharField(choices=[('pending', 'Pending'), ('ok', 'Ok'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('medical_notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('suspended', 'Suspended'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('baby_birth_date', models.DateField(blank=True, null=True)),
                ('baby_gestational_age_weeks', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('baby_birth_weight_g', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('center_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='donacion.collectioncenter')),
            ],
        ),
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consent_number', models.CharField(max_length=20, unique=True)),
                ('signature_date', models.DateField()),
                ('address', models.TextField()),
                ('bottles_to_print', models.IntegerField()),
                ('serology_requested', models.BooleanField(default=True)),
                ('photo_permission', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], default='active', max_length=20)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('end_reason', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donor_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consents', to='donacion.donacion')),
            ],
        ),
        migrations.CreateModel(
            name='SerologyStudy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('study_type', models.CharField(choices=[('hiv', 'HIV'), ('hep_b', 'Hepatitis B'), ('hep_c', 'Hepatitis C'), ('htlv_i_ii', 'HTLV I/II'), ('toxoplasmosis', 'Toxoplasmosis'), ('chagas', 'Chagas'), ('vdrl', 'VDRL')], max_length=20)),
                ('result', models.CharField(choices=[('pending', 'Pending'), ('ok', 'Ok'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('sample_date', models.DateField(blank=True, null=True)),
                ('result_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donor_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='serology_studies', to='donacion.donacion')),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visit_date', models.DateTimeField()),
                ('volume_raw_ml', models.DecimalField(decimal_places=2, max_digits=8)),
                ('notes', models.TextField(blank=True, null=True)),
                ('next_visit_due', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('center_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='donacion.collectioncenter')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='donacion.donacion')),
                ('responsible_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auditoria.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('monday', models.BooleanField(default=False)),
                ('tuesday', models.BooleanField(default=False)),
                ('wednesday', models.BooleanField(default=False)),
                ('thursday', models.BooleanField(default=False)),
                ('friday', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('center_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='donacion.collectioncenter')),
            ],
            options={
                'verbose_name_plural': 'Zones',
            },
        ),
        migrations.AddField(
            model_name='donacion',
            name='zone_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='donacion.zone'),
        ),
    ]
